//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUBRID.Data.Driver {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CUBRID.Data.Driver.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be of type CUBRIDParameter.
        /// </summary>
        internal static string ArgumentMustBeCUBRIDParameter {
            get {
                return ResourceManager.GetString("ArgumentMustBeCUBRIDParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer index must be a valid index in buffer.
        /// </summary>
        internal static string BufferIndexMustBeValidIndexInBuffer {
            get {
                return ResourceManager.GetString("BufferIndexMustBeValidIndexInBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer is not large enough to hold the requested data.
        /// </summary>
        internal static string BufferNotLargeEnoughToHoldRequestedData {
            get {
                return ResourceManager.GetString("BufferNotLargeEnoughToHoldRequestedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing database is not supported in CUBRID. Please open a new connection instead.
        /// </summary>
        internal static string CantChangeDatabase {
            get {
                return ResourceManager.GetString("CantChangeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is already open.
        /// </summary>
        internal static string ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection must be valid and open to commit transaction.
        /// </summary>
        internal static string ConnectionMustBeValidAndOpenToCommit {
            get {
                return ResourceManager.GetString("ConnectionMustBeValidAndOpenToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUBRID data type can&apos;t be mapped to a Db type.
        /// </summary>
        internal static string CUBRIDDataTypeCantBeMappedToDbType {
            get {
                return ResourceManager.GetString("CUBRIDDataTypeCantBeMappedToDbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data offset must be a valid position in the field.
        /// </summary>
        internal static string DataOffsetMustBeValidPositionInField {
            get {
                return ResourceManager.GetString("DataOffsetMustBeValidPositionInField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataReader is already open.
        /// </summary>
        internal static string DataReaderIsAlreadyOpen {
            get {
                return ResourceManager.GetString("DataReaderIsAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbType can&apos;t be mapped to a CUBRID data type.
        /// </summary>
        internal static string DbTypeCantBeMappedToCUBRIDDataType {
            get {
                return ResourceManager.GetString("DbTypeCantBeMappedToCUBRIDDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define whether trace information is logged.
        /// </summary>
        internal static string DefineWhetherTraceInformationIsLogged {
            get {
                return ResourceManager.GetString("DefineWhetherTraceInformationIsLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t know how to write the parameter.
        /// </summary>
        internal static string DontKnowHowToWriteParameter {
            get {
                return ResourceManager.GetString("DontKnowHowToWriteParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading LOB content.
        /// </summary>
        internal static string ErrorReadingLOBContent {
            get {
                return ResourceManager.GetString("ErrorReadingLOBContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writting LOB content.
        /// </summary>
        internal static string ErrorWrittingLOBContent {
            get {
                return ResourceManager.GetString("ErrorWrittingLOBContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBytes() can be called only on binary (BLOB, CLOB) columns.
        /// </summary>
        internal static string GetBytesCanBeCalledOnlyOnBinaryColumns {
            get {
                return ResourceManager.GetString("GetBytesCanBeCalledOnlyOnBinaryColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of filters were specified.
        /// </summary>
        internal static string IncorrectNumberOfFilters {
            get {
                return ResourceManager.GetString("IncorrectNumberOfFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to read data when reader is not open.
        /// </summary>
        internal static string InvalidAttemptToReadDataWhenReaderNotOpen {
            get {
                return ResourceManager.GetString("InvalidAttemptToReadDataWhenReaderNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid buffer position.
        /// </summary>
        internal static string InvalidBufferPosition {
            get {
                return ResourceManager.GetString("InvalidBufferPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection parameter.
        /// </summary>
        internal static string InvalidConnectionParameter {
            get {
                return ResourceManager.GetString("InvalidConnectionParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection port.
        /// </summary>
        internal static string InvalidConnectionPort {
            get {
                return ResourceManager.GetString("InvalidConnectionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection string.
        /// </summary>
        internal static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LOB Position.
        /// </summary>
        internal static string InvalidLOBPosition {
            get {
                return ResourceManager.GetString("InvalidLOBPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property name.
        /// </summary>
        internal static string InvalidPropertyName {
            get {
                return ResourceManager.GetString("InvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid query type.
        /// </summary>
        internal static string InvalidQueryType {
            get {
                return ResourceManager.GetString("InvalidQueryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Timeout value! Expected a value between 1 and 99.
        /// </summary>
        internal static string InvalidTimeoutValue {
            get {
                return ResourceManager.GetString("InvalidTimeoutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filters were specified.
        /// </summary>
        internal static string NoFiltersSpecified {
            get {
                return ResourceManager.GetString("NoFiltersSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to change the &apos;ConnectionString&apos; property while the connection state is.
        /// </summary>
        internal static string NotAllowedToChangeConnectionStringWhenStateIs {
            get {
                return ResourceManager.GetString("NotAllowedToChangeConnectionStringWhenStateIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to change the &apos;ConnectionTimeout&apos; property while the connection state is.
        /// </summary>
        internal static string NotAllowedToChangeConnectionTimeoutWhenStateIs {
            get {
                return ResourceManager.GetString("NotAllowedToChangeConnectionTimeoutWhenStateIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to change the &apos;LockTimeout&apos; property while the connection state is.
        /// </summary>
        internal static string NotAllowedToChangeLockTimeoutWhenStateIs {
            get {
                return ResourceManager.GetString("NotAllowedToChangeLockTimeoutWhenStateIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all parameters are bound.
        /// </summary>
        internal static string NotAllParametersAreBound {
            get {
                return ResourceManager.GetString("NotAllParametersAreBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid LOB type.
        /// </summary>
        internal static string NotAValidLOBType {
            get {
                return ResourceManager.GetString("NotAValidLOBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported in CUBRID.
        /// </summary>
        internal static string NotSupportedInCUBRID {
            get {
                return ResourceManager.GetString("NotSupportedInCUBRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only CUBRIDParameter objects are valid.
        /// </summary>
        internal static string OnlyCUBRIDParameterObjectsAreValid {
            get {
                return ResourceManager.GetString("OnlyCUBRIDParameterObjectsAreValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter already added to the collection.
        /// </summary>
        internal static string ParameterAlreadyAdded {
            get {
                return ResourceManager.GetString("ParameterAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name must start with &apos;?&apos;.
        /// </summary>
        internal static string ParameterNameMustStartWith {
            get {
                return ResourceManager.GetString("ParameterNameMustStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not found in the collection.
        /// </summary>
        internal static string ParameterNotFound {
            get {
                return ResourceManager.GetString("ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter not found in collection. You should add &apos;?&apos; to the parameter name before searching..
        /// </summary>
        internal static string ParameterNotFoundMissingPrefix {
            get {
                return ResourceManager.GetString("ParameterNotFoundMissingPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters must be named.
        /// </summary>
        internal static string ParametersMustBeNamed {
            get {
                return ResourceManager.GetString("ParametersMustBeNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultset is closed.
        /// </summary>
        internal static string ResultsetIsClosed {
            get {
                return ResourceManager.GetString("ResultsetIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection is not open.
        /// </summary>
        internal static string TheConnectionIsNotOpen {
            get {
                return ResourceManager.GetString("TheConnectionIsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection property has not been set.
        /// </summary>
        internal static string TheConnectionPropertyHasNotBeenSet {
            get {
                return ResourceManager.GetString("TheConnectionPropertyHasNotBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has already been committed or is not pending.
        /// </summary>
        internal static string TransactionAlreadyCommittedOrNotPending {
            get {
                return ResourceManager.GetString("TransactionAlreadyCommittedOrNotPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown isolation level is not supported.
        /// </summary>
        internal static string UnknownIsolationLevelNotSupported {
            get {
                return ResourceManager.GetString("UnknownIsolationLevelNotSupported", resourceCulture);
            }
        }
    }
}
